### ISSUE TITLE
Tanke

### ISSUE THREAD

**Issue by ntijoh-daniel-berg** [David-Dahlstrom-nti-johanneberg/Do_Crash#10]
Antar att landaren är en cirkel.

Om man sätter en punkt till mitten av landaren  (image.width /2, image.height + 2) och har en radie på cirkeln borde man kunna göra mitten + radien istället

https://github.com/David-Dahlstrom-nti-johanneberg/Do_Crash/blob/c989e2848d70f85b9ee33e5e2189f3ebcc2ae422/oogabooga/lunarLander.rb#L18

**Comment by coaltroll** [comment]
vi skapade både en circle och box collider
