### ISSUE TITLE
använd #each

### ISSUE THREAD

**Issue by ntijoh-daniel-berg** [David-Dahlstrom-nti-johanneberg/Do_Crash#6]
https://github.com/David-Dahlstrom-nti-johanneberg/Do_Crash/blob/c989e2848d70f85b9ee33e5e2189f3ebcc2ae422/oogabooga/floor.rb#L115

**Comment by ntijoh-daniel-berg** [comment]
Dito https://github.com/David-Dahlstrom-nti-johanneberg/Do_Crash/blob/c989e2848d70f85b9ee33e5e2189f3ebcc2ae422/oogabooga/floor.rb#L125

**Comment by coaltroll** [comment]
den andra är "0..@ls.length"
".." inte "..."
kan inte använda .each
annars fixat
