### ISSUE TITLE
Väldigt stor metod

### ISSUE THREAD

**Issue by ntijoh-daniel-berg** [David-Dahlstrom-nti-johanneberg/Do_Crash#7]
Dela upp i mindre?

https://github.com/David-Dahlstrom-nti-johanneberg/Do_Crash/blob/c989e2848d70f85b9ee33e5e2189f3ebcc2ae422/oogabooga/floor.rb#L61

**Comment by coaltroll** [comment]
lite svårt att göra den mindre och lika läsbar pga av att delarna använder variabler från varandra. Men jag förkortade första delen iaf.
