### ISSUE TITLE
Är denna användbar här?

### ISSUE THREAD

**Issue by ntijoh-daniel-berg** [David-Dahlstrom-nti-johanneberg/Do_Crash#9]
https://www.rubydoc.info/gems/gosu/Gosu.offset_x

https://github.com/David-Dahlstrom-nti-johanneberg/Do_Crash/blob/c989e2848d70f85b9ee33e5e2189f3ebcc2ae422/oogabooga/landers.rb#L31-L32

**Comment by coaltroll** [comment]
kan inte få den att funka och tycker att det är svårare att förstå, inte värt att implementera.
